let

    funcao = 
    // ------------------------------------------------------------------- INICIO DA FUNCAO -------------------------------------------------------------------


        (
            workspace_nome as text,
            fluxo_nome as text,
            tabela_nome as text
        )=>

        let 
            pbix_flows = PowerPlatform.Dataflows(),
            pbix_entidade = 
                Table.SelectRows(
                    Table.SelectRows(
                            Table.SelectRows(
                                pbix_flows, 
                                each [workspaceName] = workspace_nome
                            )[Data]{0}, 
                            each [dataflowName] = fluxo_nome
                    )[Data]{0}, 
                    each [entity] = tabela_nome
                )[Data]{0}
        in   
            pbix_entidade


    // ------------------------------------------------------------------- FIM DA FUNCAO -------------------------------------------------------------------

        , metadados = [
            Documentation.Name  = "fxExplodeDataFlow",
            Documentation.Description = "
                by Joviano Silveira (www.joviano.com)
                Você busca uma tabela de um fluxo de dados sem precisar passar o ID (hash), e com isso, se um dia você deletar sem querer, basta republicar, que todos seus BI estarão funcionando, pois essa sução funciona pelo NOME DAS ENTIDADES",
            
            Documentation.Examples = {

                // exemplo 01
                [
                    Description = "descricao do exemplo 1",
                    Code = "
                    
                        fxExplodeDataFlow(NOME_DO_WORKSPACE, NOME_DO_FLUXO_DE_DADOS, NOME_DA_TABELA)                
                        
                    ",
                    Result = "

                        | SUA TABELA |

                    "
                ]

            }
        ]

in

    Value.ReplaceType(
        funcao,
        Value.ReplaceMetadata(
            Value.Type(funcao),metadados
        )
    )